name: ECR Build Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Images
        run: docker build -t devops-demo:v1 .

      - name: Tag Image
        run: docker tag devops-demo:v1 574644334284.dkr.ecr.ap-south-1.amazonaws.com/devops-demo:v1

      - name: Push Image
        run: docker push 574644334284.dkr.ecr.ap-south-1.amazonaws.com/devops-demo:v1

      - name: Update kubeconfig
              run: | aws eks update-kubeconfig --region ap-south-1 --name devops-eks-cluster

      - name: Deploy to EKS
        run: | kubectl apply -f deployment.yaml

      - name: Restart Deployment
        run: | kubectl rollout restart deployment devops-demo
